"""Add state enum to Car

Revision ID: 3d23a194dbc3
Revises: 
Create Date: 2025-07-13 15:46:08.840741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d23a194dbc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('AVAILABLE', 'RENTED', 'DELETED', name='carstate'), nullable=False))
        batch_op.drop_constraint(batch_op.f('cars_merchant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['merchant_id'], ['id'])
        batch_op.drop_column('available')

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rental_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rental_car_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'cars', ['car_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('rental', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rental_car_id_fkey'), 'cars', ['car_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('rental_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cars_merchant_id_fkey'), 'users', ['merchant_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
